config/routes.rb
Rails.application.routes.draw do

  resources :projects

  resources :countertops
  resources :granitecolors
  root 'pages#home'

  devise_for :users, controllers: { registrations: "registrations" }

  get 'users/dashboard' => 'users#dashboard'

end

app/models/granitecolor.rb
class Granitecolor < ActiveRecord::Base
	has_one :countertop
end

app/controllers/granitecolors_controller.rb
class GranitecolorsController < ApplicationController
 before_action :set_granitecolor, only: [:show, :edit, :update, :destroy]

	def index
    	@granitecolors = Granitecolor.all
  	end


	def show
	    @granitecolors = Granitecolor.all 
	end

	def edit
	    @granitecolors = Granitecolor.all 
	end

	def new
	    @granitecolor = Granitecolor.new
	end

	def create
    @granitecolor = Granitecolor.new(granitecolor_params)
    
    respond_to do |format|
      if @granitecolor.save
        format.html { redirect_to @granitecolor, notice: 'Granite color was successfully created.' }
        format.json { render :show, status: :created, location: @granitecolor }
      else
        format.html { render :new }
        format.json { render json: @granitecolor.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @granitecolor.update(granitecolor_params)
        format.html { redirect_to @granitecolor, notice: 'Granite color was successfully updated.' }
        format.json { render :show, status: :ok, location: @granitecolor }
      else
        format.html { render :edit }
        format.json { render json: @granitecolor.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @granitecolor.destroy
    respond_to do |format|
      format.html { redirect_to granitecolors_url, notice: 'Granite color was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_granitecolor
      @granitecolor = Granitecolor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def granitecolor_params
      params.require(:granitecolor).permit(:name, :url)
    end
end

app/views/granitecolors/_form.html.erb
<%= form_for @granitecolor do |f| %>
 <% if @granitecolor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@granitecolor.errors.count, "error") %> prohibited this Granitecolor from being saved:</h2>

      <ul>
      <% @granitecolor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group" align="left">
    <%= f.label :name, "Enter the name of your Granitecolor" %>
    <%= f.text_field :name, class: "form-control", placeholder: "Enter your Granite Color" %>
</div>

<div class="form-group" align="left">
    <%= f.label :url, "Enter the URL of the Granitecolor sample" %>
    <%= f.text_field :url, class: "form-control", placeholder: "Enter the URL" %>
</div>

 <div class="form-group">
    <%= f.submit class: "btn btn-primary btn-lg" %>
 </div>

<% end %>

app/views/granitecolors/edit.html.erb
<h1>Edit your Granite Colors</h1>

<%= render 'form' %>

<%= link_to 'Show', @granitecolor %> |
<%= link_to 'Back', granitecolors_path %>

app/views/granitecolors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Index of All Granite Colors</h1>

<table>
  <thead>
    <tr>
    
      <th>Name</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @granitecolors.each do |granitecolor| %>
      <tr>
        <td><%= granitecolor.name %></td>
        <th colspan="3"></th>
    	<td><%= granitecolor.url %></td>
    
        <td><%= link_to 'Show', granitecolor %></td>
        <td><%= link_to 'Edit', edit_granitecolor_path(granitecolor) %></td>
        <td><%= link_to 'Destroy', granitecolor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Granitecolor', new_granitecolor_path %>

app/views/granitecolors/new.html.erb
new.html.erb

app/views/granitecolors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @granitecolor.name %>
</p>

<p>
  <strong>URL:</strong>
  <%= @granitecolor.url %>
</p>


<%= link_to 'Edit', edit_granitecolor_path(@granitecolor) %> |
<%= link_to 'Back', granitecolors_path %>