config/routes.rb
Rails.application.routes.draw do

  resources :projects

  resources :countertops
  resources :granitecolors
  root 'pages#home'

  devise_for :users, controllers: { registrations: "registrations" }

  get 'users/dashboard' => 'users#dashboard'

end

app/models/countertop.rb
class Countertop < ActiveRecord::Base
	belongs_to :countertype
	belongs_to :granitecolor
	belongs_to :marblecolor
	belongs_to :soapstonecolor
	belongs_to :quartzcolor
	belongs_to :layout
	belongs_to :project

end

app/controllers/countertops_controller.rb
class CountertopsController < ApplicationController
  before_action :set_countertop, only: [:show, :edit, :update, :destroy]

 
  # GET /countertops
  # GET /countertops.json
  def index
    @countertops = Countertop.all
    @countertops = Countertop.includes(:countertype).all
    @countertops = Countertop.includes(:granitecolor).all
    @countertops = Countertop.includes(:marblecolor).all
    @granitecolors = Granitecolor.all 
    @marblecolors = Marblecolor.all 
    @soapstonecolors = Soapstonecolor.all 
    @quartzcolors = Quartzcolor.all 
    @layouts = Layout.all 
    
  end

  # GET /countertops/1
  # GET /countertops/1.json
  def show
    @countertops = Countertop.all
    @countertops = Countertop.includes(:countertype).all
    @countertops = Countertop.includes(:granitecolor).all
    @countertops = Countertop.includes(:marblecolor).all
    @countertops = Countertop.includes(:soapstonecolor).all
    @countertops = Countertop.includes(:quartzcolor).all
    @countertops = Countertop.includes(:layout).all
   
  end

  # GET /countertops/new
  def new
    @countertop = Countertop.new
    @granitecolors = Granitecolor.all 
    @marblecolors = Marblecolor.all
    @soapstonecolors = Soapstonecolor.all
    @quartzcolors = Quartzcolor.all 
    @layouts = Layout.all 
  end

  # GET /countertops/1/edit
  def edit
    @countertops = Countertop.all
    @countertops = Countertop.includes(:countertype).all
    @countertops = Countertop.includes(:granitecolor).all
    @countertops = Countertop.includes(:marblecolor).all
    @granitecolors = Granitecolor.all 
    @marblecolors = Marblecolor.all 
    @soapstonecolors = Soapstonecolor.all
    @quartzcolors = Quartzcolor.all 
    @layouts = Layout.all 
  end

  # POST /countertops
  # POST /countertops.json
  def create
    @countertop = Countertop.new(countertop_params)
    @granitecolors = Granitecolor.all 
    @marblecolors = Marblecolor.all
    @soapstonecolors = Soapstonecolor.all
    @quartzcolors = Quartzcolor.all 
    @layouts = Layout.all 
    


    respond_to do |format|
      if @countertop.save
        format.html { redirect_to @countertop, notice: 'Countertop was successfully created.' }
        format.json { render :show, status: :created, location: @countertop }
      else
        format.html { render :new }
        format.json { render json: @countertop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countertops/1
  # PATCH/PUT /countertops/1.json
  def update
    respond_to do |format|
      if @countertop.update(countertop_params)
        format.html { redirect_to @countertop, notice: 'Countertop was successfully updated.' }
        format.json { render :show, status: :ok, location: @countertop }
      else
        format.html { render :edit }
        format.json { render json: @countertop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countertops/1
  # DELETE /countertops/1.json
  def destroy
    @countertop.destroy
    respond_to do |format|
      format.html { redirect_to countertops_url, notice: 'Countertop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_countertop
      @countertop = Countertop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def countertop_params
      params.require(:countertop).permit(:counterzip, :countersize, :countertype_id, :granitecolor_id, 
        :marblecolor_id, :soapstonecolor_id, :quartzcolor_id, :layout_id, :countertext, :countertime)
    end
end

app/helpers/countertops_helper.rb
module CountertopsHelper
end

app/views/countertops/_form.html.erb
<%= form_for @countertop do |f| %>
 <% if @countertop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@countertop.errors.count, "error") %> prohibited this Countertop Project from being saved:</h2>

      <ul>
      <% @countertop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group" align="left">
    <%= f.label :counterzip, "Tell us where your countertop project is going." %>
    <%= f.text_field :counterzip, class: "form-control", placeholder: "Enter your Zip Code" %>
</div>

<div id="countertype" class="form-group" align="left">
    <%= f.label :countertype_id, "What type of countertop material do you need?" %></br>
    <%= f.collection_select :countertype_id, Countertype.all, :id, :name, { :prompt => "Select Your Material" }, class: "input-sm"  %>
</div>

<div class="form-group", align="left">
    <%= f.label :countersize, "How much countertop do you need?" %>
    <%= f.text_field :countersize, class: "form-control", placeholder: "Enter the amount of countertop you need in square feet" %>
</div>

<div id="layout" align="left" class="form-group" style="display:none;">
    <%= f.label :layout_id, "What is your countertop layout?" %></br>
    <div class="imagebox">
    <%= f.select :layout_id, options_for_select(@layouts.map{ |l| [l.name, l.id, {'data-img-src'=>l.url}]}) %>
  </div>
</div>

<div id="granitecolor" align="left" class="form-group" style="display:none;">
    <%= f.label :granitecolor_id, "What granite color pattern do you want?" %></br>
    <div class="imagebox" style="height:450px; width:80%; overflow:auto;">
      <%= f.select :granitecolor_id, options_for_select(@granitecolors.map{ |g| [g.name, g.id, {'data-img-src'=>g.url}]}) %>
  </div>
</div>

<div id="marblecolor" align="left" class="form-group" style="display:none;">
    <%= f.label :marblecolor_id, "What marble color pattern do you want?" %></br>
    <div class="imagebox" style="height:450px; width:80%; overflow:auto;">
     <%= f.select :marblecolor_id, options_for_select(@marblecolors.map{ |m| [m.name, m.id, {'data-img-src'=>m.url}] }) %>
    </div>
</div>

<div id="soapstonecolor" align="left" class="form-group" style="display:none;">
    <%= f.label :soapstonecolor_id, "What soapstone color pattern do you want?" %></br>
  <div class="imagebox" style="height:350px; width:80%; overflow:auto;">
    <%= f.select :soapstonecolor_id, options_for_select(@soapstonecolors.map{ |s| [s.name, s.id, {'data-img-src'=>s.url}] }) %>
  </div>
</div>

<div id="quartzcolor" align="left" class="form-group" style="display:none;">
    <%= f.label :quartzcolor_id, "What quartz color pattern do you want?" %></br>
    <%= f.select :quartzcolor_id, options_for_select(@quartzcolors.map{ |q| [q.name, q.id, {'data-img-src'=>q.url}] }) %>
</div>

<div align="left">
  <label>How Soon Do You Need your Countertop?</label>
<div class="radio">
  <%= f.radio_button :countertime, '1-2 Weeks' %>
  <label>1-2 Weeks</label></br>
  <%= f.radio_button :countertime, '2-4 Weeks' %>
  <label>2-4 Weeks</label></br>
  <%= f.radio_button :countertime, '4-6 Weeks' %>
  <label>4-6 Weeks</label></br>
  <%= f.radio_button :countertime, 'More Than 6 Weeks' %>
  <label>More Than 6 Weeks</label>
</div> 
</div>


<div class="form-group" align="left" style="height: 250px;">
    <%= f.label :countertext, "Tell us more about your project if you think it will help." %> 
    <%= f.text_area :countertext, cols: 80, rows: 5, class: "form-control", placeholder: "Provide additional info here." %>
</div>

 <div class="form-group">
    <%= f.submit class: "btn btn-primary btn-lg" %>
 </div>

<% end %>

app/views/countertops/edit.html.erb
<h1>Edit your Countertop Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @countertop %> |
<%= link_to 'Back', countertops_path %>

app/views/countertops/index.html.erb
<p id="notice"><%= notice %></p>



<h1>Index of All Countertop Projects</h1>

<table>
  <thead>
    <tr>
      <th>Zip Code</th>
      <th>Countertop Type</th>
      <th>Size</th>
      <th>Color</th>
     
      <th colspan="3"></th>
    </tr>
  </thead>


  <tbody>
    <% @countertops.each do |countertop| %>
      <tr>
        <td><%= countertop.counterzip %></td>
    	  <td><%= countertop.countertype.name if countertop.countertype !=nil %></td>
        <td><%= countertop.countersize %></td>
        <td><%= countertop.granitecolor.name if countertop.granitecolor !=nil %></td>
        <td><%= countertop.marblecolor.name if countertop.marblecolor !=nil %></td>
       
        <td><%= link_to 'Show', countertop %></td>
        <td><%= link_to 'Edit', edit_countertop_path(countertop) %></td>
        <td><%= link_to 'Destroy', countertop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Countertop', new_countertop_path %>

app/views/countertops/new.html.erb
<h1>Create Your New Countertop Project</h1>

<%= render 'form' %>

<%= link_to 'Back', countertops_path %>

app/views/countertops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Zip Code:</strong>
  <%= @countertop.counterzip %>
</p>

<p>
  <strong>Counter Type:</strong>
  <%= @countertop.countertype.name %>
</p>

<p>
  <strong>Size:</strong>
  <%= @countertop.countersize %>
</p>

</p>
  <strong>Countertop Color:</strong>
  <%= @countertop.granitecolor.name if @countertop.granitecolor !=nil %></br> 
  <%= @countertop.marblecolor.name if @countertop.marblecolor !=nil %>
</p>

<p>
  <strong>Timeframe:</strong>
  <%= @countertop.countertime %>
</p>


<%= link_to 'Edit', edit_countertop_path(@countertop) %> |
<%= link_to 'Back', countertops_path %>